INSERT INTO dishes (description, image_url, name, price, category_id, restaurant_id) VALUES
("Eggplant or potato-based meal with minced meat.", "/images/menu/moussaka.jpg", "Moussaka", 5.00, 3, 1),
("Stacked layers of lasagna with filling of ground meat, tomato and bechamel sauce.", "/images/menu/lasagne.jpg", "Lasagne", 6.00, 3, 1),
("Spongy baked dish made by adding flavoured egg yolks to stiffly beaten egg whites.", "/images/menu/souffle.jpg", "Souffle", 5.00, 4, 3),
("Tomatoes, cucumbers, onion, raw/roasted peppers and sirene dressed with sunflower oil, vinegar and salt.", "/images/menu/shopska-salad.jpg", "Shopska salad", 7.00, 1, 2),
("Tomatoes, cucumbers, onion, feta cheese and olives dressed with salt, oregano, lemon juice and olive oil.", "/images/menu/greek-salad.jpg", "Greek salad", 8.00, 1, 3),
("Chicken broth with pieces of chicken, pasta, carrots, onion, and grains such as rice.", "/images/menu/chicken-soup.jpg", "Chicken soup", 4.00, 2, 2),
("Clear broth with whole meatballs, vegetables, pasta or grains such as rice.", "/images/menu/meat-balls-soup.jpg", "Meat balls soup", 3.00, 2, 3),
("Fried dough product with filling.", "/images/menu/pancakes.jpg", "Pancakes", 4.00, 4, 3),
("Well-cooked and finely chopped beef or lamb tripe with spices such as garlic, vinegar and hot peppers.", "/images/menu/shkembe-chorba.jpg", "Shkembe chorba", 5.00, 2, 2),
("A dish baked in the oven in casseroles, which contains chicken meat, onions, savory, peppers, salt.", "/images/menu/kavarma.jpeg", "Kavarma", 7.00, 3, 3),
("Coarsely grated potatoes, onions, salt and mint and knead everything and bake over low heat.", "/images/menu/patatnik.jpg", "Patatnik", 9.00, 3, 2),
("Corn semolina or coarsely ground cornmeal with cheese, eggs or meat.", "/images/menu/kachamak.jpg", "Kachamak", 8.00, 3, 1),
("A clay casserole in which onions, tomatoes, brine cheese, green pepper, garlic, etc. are added.", "/images/menu/shopski-cheese.jpg", "Shopski cheese", 6.00, 3, 1),
("Egg custard dessert with a layer of soft caramel.", "/images/menu/creme-caramel.jpg", "Crème caramel", 4.00, 4, 3),
("Dessert of egg custard, sprinkled with sugar, which is caramelized with a burner.", "/images/menu/creme-brule.jpg", "Crème brûlée", 5.00, 4, 3),
("Sliced cucumbers, tomatoes, onions, parsley, roasted or raw peppers, ham, boiled egg, yellow cheese, grated sirene", "/images/menu/ovcharska-salad.jpg", "Ovcharska salad", 8.00, 1, 2);