spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

server:
  port: 8090

mail:
  homedelivery: "homedeliveryteambulgaria@gmail.com"
  host: smtp.gmail.com
  port: 25
  username: ${mail_user}
  password: ${mail_password}