spring:
  datasource:
    url: jdbc:hsqldb:mem:home_delivery;sql.syntax_mys=true
    driver-class-name: org.hsqldb.jdbcDriver
    username: test
    password: test
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

server:
  port: 8090

mail:
  homedelivery: "homedeliveryteambulgaria@example.com"
  host: localhost
  port: 3333
  username: test@example.com
  password: topsecret